GET http://localhost:8081/user/2

###
DELETE http://localhost:8081/user/2

###
GET http://localhost:8081/users/list/

###

POST http://localhost:8081/user/
Content-Type: application/json

{
  "name": "wfetgryh",
  "phone": "0987654321"
}

###

POST http://localhost:8081/user/
Content-Type: application/json

{
  "name": "Vasya",
  "phone": "1234567890"
}

###

POST http://localhost:8081/user/
Content-Type: application/json

{
  "name": "Vasya",
  "phone": "sbethtrj"
}

###
